#ifndef TERMI_ARM64_DECODER_H
#define TERMI_ARM64_DECODER_H

#include <stdint.h>

typedef enum {
    ARM64_INSN_UNKNOWN = 0,

    ARM64_INSN_ADD_IMM,
    ARM64_INSN_SUB_IMM,
    ARM64_INSN_ADD_REG,
    ARM64_INSN_SUB_REG,
    ARM64_INSN_SUBS_REG,
    ARM64_INSN_AND_REG,
    ARM64_INSN_ORR_REG,
    ARM64_INSN_EOR_REG,
    ARM64_INSN_ORN_REG,
    ARM64_INSN_BIC_REG,
    ARM64_INSN_MVN_REG,
    ARM64_INSN_NEG_REG,
    ARM64_INSN_AND_IMM,
    ARM64_INSN_ORR_IMM,
    ARM64_INSN_EOR_IMM,
    ARM64_INSN_ANDS_IMM,
    ARM64_INSN_LSL_REG,
    ARM64_INSN_LSR_REG,
    ARM64_INSN_ASR_REG,
    ARM64_INSN_MUL,
    ARM64_INSN_UDIV,
    ARM64_INSN_SDIV,

    ARM64_INSN_MOV_REG,
    ARM64_INSN_MOVZ,
    ARM64_INSN_MOVK,
    ARM64_INSN_MOVN,

    ARM64_INSN_LDR_IMM,
    ARM64_INSN_LDRB_IMM,
    ARM64_INSN_LDRH_IMM,
    ARM64_INSN_LDRSB_IMM,
    ARM64_INSN_LDRSH_IMM,
    ARM64_INSN_LDRSW_IMM,
    ARM64_INSN_STR_IMM,
    ARM64_INSN_STRB_IMM,
    ARM64_INSN_STRH_IMM,

    ARM64_INSN_LDR_REG,
    ARM64_INSN_STR_REG,
    ARM64_INSN_LDR_VREG,
    ARM64_INSN_STR_VREG,

    ARM64_INSN_LDUR,
    ARM64_INSN_LDURB,
    ARM64_INSN_LDURH,
    ARM64_INSN_LDURSB,
    ARM64_INSN_LDURSH,
    ARM64_INSN_LDURSW,
    ARM64_INSN_STUR,
    ARM64_INSN_STURB,
    ARM64_INSN_STURH,

    ARM64_INSN_LDUR_PRE,
    ARM64_INSN_LDUR_POST,
    ARM64_INSN_STUR_PRE,
    ARM64_INSN_STUR_POST,

    ARM64_INSN_LDR_PRE,
    ARM64_INSN_LDR_POST,
    ARM64_INSN_STR_PRE,
    ARM64_INSN_STR_POST,

    ARM64_INSN_LDP,
    ARM64_INSN_STP,
    ARM64_INSN_LDP_PRE,
    ARM64_INSN_LDP_POST,
    ARM64_INSN_STP_PRE,
    ARM64_INSN_STP_POST,

    ARM64_INSN_B,
    ARM64_INSN_BL,
    ARM64_INSN_BR,
    ARM64_INSN_BLR,
    ARM64_INSN_RET,

    ARM64_INSN_BEQ,
    ARM64_INSN_BNE,
    ARM64_INSN_BGT,
    ARM64_INSN_BLT,
    ARM64_INSN_BGE,
    ARM64_INSN_BLE,
    ARM64_INSN_BHI,
    ARM64_INSN_BLS,

    ARM64_INSN_CBZ,
    ARM64_INSN_CBNZ,
    ARM64_INSN_TBZ,
    ARM64_INSN_TBNZ,

    ARM64_INSN_CMP_IMM,
    ARM64_INSN_CMP_REG,
    ARM64_INSN_TST_REG,

    ARM64_INSN_CSEL,
    ARM64_INSN_CSINC,
    ARM64_INSN_CSINV,
    ARM64_INSN_CSNEG,

    ARM64_INSN_ADRP,
    ARM64_INSN_ADR,

    ARM64_INSN_UBFM,
    ARM64_INSN_SBFM,
    ARM64_INSN_BFM,
    ARM64_INSN_EXTR,
    ARM64_INSN_LSL_IMM,
    ARM64_INSN_LSR_IMM,
    ARM64_INSN_ASR_IMM,
    ARM64_INSN_ROR_IMM,

    ARM64_INSN_MADD,
    ARM64_INSN_MSUB,
    ARM64_INSN_SMADDL,
    ARM64_INSN_UMULL,
    ARM64_INSN_SMULL,
    ARM64_INSN_SMULH,
    ARM64_INSN_UMULH,

    ARM64_INSN_CMN_IMM,
    ARM64_INSN_CMN_REG,
    ARM64_INSN_ADDS_IMM,
    ARM64_INSN_ADDS_REG,
    ARM64_INSN_SUBS_IMM,
    ARM64_INSN_ANDS_REG,
    ARM64_INSN_SBC,
    ARM64_INSN_ADC,

    ARM64_INSN_CSET,
    ARM64_INSN_CSETM,
    ARM64_INSN_CINC,
    ARM64_INSN_CINV,
    ARM64_INSN_CNEG,
    ARM64_INSN_CCMP_IMM,
    ARM64_INSN_CCMP_REG,
    ARM64_INSN_CCMN_IMM,
    ARM64_INSN_CCMN_REG,

    ARM64_INSN_REV,
    ARM64_INSN_REV16,
    ARM64_INSN_REV32,
    ARM64_INSN_CLZ,
    ARM64_INSN_CLS,
    ARM64_INSN_RBIT,
    ARM64_INSN_ROR_REG,

    ARM64_INSN_LDAXR,
    ARM64_INSN_LDXR,
    ARM64_INSN_STLXR,
    ARM64_INSN_STXR,
    ARM64_INSN_LDAXRB,
    ARM64_INSN_LDAXRH,
    ARM64_INSN_STLXRB,
    ARM64_INSN_STLXRH,

    ARM64_INSN_MRS,
    ARM64_INSN_MSR,
    ARM64_INSN_DMB,
    ARM64_INSN_DSB,
    ARM64_INSN_ISB,

    ARM64_INSN_FMOV_REG,
    ARM64_INSN_FMOV_IMM,
    ARM64_INSN_FMOV_GPR_TO_VEC,
    ARM64_INSN_FMOV_VEC_TO_GPR,
    ARM64_INSN_FADD,
    ARM64_INSN_FSUB,
    ARM64_INSN_FMUL,
    ARM64_INSN_FDIV,
    ARM64_INSN_FNEG,
    ARM64_INSN_FABS,
    ARM64_INSN_FSQRT,
    ARM64_INSN_FCMP,
    ARM64_INSN_FCMPE,
    ARM64_INSN_FCSEL,
    ARM64_INSN_FCVT,
    ARM64_INSN_FCVTZS,
    ARM64_INSN_FCVTZU,
    ARM64_INSN_SCVTF,
    ARM64_INSN_UCVTF,
    ARM64_INSN_FMADD,
    ARM64_INSN_FMSUB,
    ARM64_INSN_FNMUL,
    ARM64_INSN_FMIN,
    ARM64_INSN_FMAX,

    ARM64_INSN_MOVI,
    ARM64_INSN_MVNI,
    ARM64_INSN_DUP,
    ARM64_INSN_INS,
    ARM64_INSN_UMOV,
    ARM64_INSN_BIC_VEC,
    ARM64_INSN_BIF,

    ARM64_INSN_SVC,
    ARM64_INSN_BRK,
    ARM64_INSN_HLT,

    ARM64_INSN_NOP,
} arm64_insn_type_t;

typedef struct {
    arm64_insn_type_t type;
    uint32_t raw;

    uint8_t rd;
    uint8_t rn;
    uint8_t rm;
    uint8_t ra;
    uint8_t rt;
    uint8_t rt2;

    uint64_t imm;
    uint8_t shift;

    uint8_t sf;
    uint8_t cond;
    uint8_t option;

    int64_t offset;
    
    uint8_t vd;
    uint8_t vn;
    uint8_t vm;
    uint8_t va;
    uint8_t ftype;
    uint8_t opc;
    uint8_t nzcv;
    uint16_t imm16;
    uint8_t hw;
    uint8_t size;
} arm64_insn_t;

int arm64_decode(uint32_t insn, arm64_insn_t *decoded);

#endif
